language: python
python:
  - 3.7
before_install:
  - python --version
  - pip install -r requirements.txt
  - pip install -r requirements-travis.txt
script: pytest test
after_success:
  - pytest --cov=. test/