database: RamDatabase

databases:
  RamDatabase: {}
  PostgresFirebaseDatabase:
    users_table_name: "chotuve.users"
    recovery_token_table_name: "chotuve.user_recovery_token"
    postgr_host_env_name: "POSTGRES_HOST"
    postgr_user_env_name: "POSTGRES_USER"
    postgr_pass_env_name: "POSTGRES_PASS"
    postgr_database_env_name: "POSTGRES_DATABASE"
    firebase_json_env_name: "FIREBASE_JSON"
    firebase_api_key_env_name: "FIREBASE_API_KEY"