database: RamDatabase
api_key_secret_generator_env_name: API_GENERATOR_SECRET

email_service:
  sendgrid_email_env_name: "SENDGRID_EMAIL"
  sendgrid_api_key_env_name: "SENDGRID_API_KEY"

databases:
  RamDatabase: {}
  PostgresFirebaseDatabase:
    users_table_name: "chotuve.users"
    recovery_token_table_name: "chotuve.user_recovery_token"
    api_key_table_name: "chotuve.api_keys"
    api_calls_table_name: "chotuve.api_key_calls"
    postgr_host_env_name: "POSTGRES_HOST"
    postgr_user_env_name: "POSTGRES_USER"
    postgr_pass_env_name: "POSTGRES_PASS"
    postgr_database_env_name: "POSTGRES_DATABASE"
    firebase_json_env_name: "FIREBASE_JSON"
    firebase_api_key_env_name: "FIREBASE_API_KEY"